"""create users table

Revision ID: 5c5259b9550b
Revises: 
Create Date: 2025-04-11 06:42:36.900420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c5259b9550b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'deleted_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'deleted_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.create_unique_constraint(None, 'users', ['email'])
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'deleted_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('users', 'deleted_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
