"""set users.created_by and users.deleted_by as foreign keys

Revision ID: 64f4130d79ce
Revises: 0e1539616ace
Create Date: 2025-04-16 06:20:19.692602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64f4130d79ce'
down_revision: Union[str, None] = '0e1539616ace'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'users', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'users', 'users', ['deleted_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    # ### end Alembic commands ###
